language: python
matrix:
    include:
        - env: TOXENV=py27
        - env: TOXENV=py35
          python: 3.5
        - env: TOXENV=py36
          python: 3.6
        - env: TOXENV=pypy
install: pip install tox
script: tox
cache:
    directories:
        - $HOME/.cache/pip
        - $HOME/.pre-commit
