language: python
matrix:
    include:
        - env: TOXENV=py27
        - env: TOXENV=py35
          python: 3.5
        - env: TOXENV=py36
          python: 3.6
        - env: TOXENV=pypy
install:
    - pip install -r requirements-dev.txt
    - pip install -r requirements.txt 
script:
    - coverage run -m py.test tests/
    - pre-commit run --all-files
    - check-requirements
cache:
    directories:
        - $HOME/.cache/pip
        - $HOME/.pre-commit
